package com.javdin.demo;

import javax.xml.transform.*;
import javax.xml.transform.stream.*;
import java.io.*;
import java.nio.file.*;

/**
 * Converts an existing AST XML file to HTML visualization.
 * This is useful for visualizing AST files generated by optimization tools.
 * 
 * Usage:
 *   mvn exec:java -Dexec.mainClass="com.javdin.demo.AstXmlToHtmlConverter" \
 *                 -Dexec.args="ast-before-optimization.xml"
 */
public class AstXmlToHtmlConverter {
    
    public static void main(String[] args) {
        if (args.length == 0) {
            System.err.println("Usage: AstXmlToHtmlConverter <ast-xml-file>");
            System.err.println();
            System.err.println("Example:");
            System.err.println("  mvn exec:java -Dexec.mainClass=\"com.javdin.demo.AstXmlToHtmlConverter\" \\");
            System.err.println("                -Dexec.args=\"ast-before-optimization.xml\"");
            System.exit(1);
        }
        
        String xmlFile = args[0];
        
        try {
            // Verify XML file exists
            if (!Files.exists(Paths.get(xmlFile))) {
                System.err.println("ERROR: File not found: " + xmlFile);
                System.exit(1);
            }
            
            System.out.println("==============================================================");
            System.out.println("       AST XML to HTML Converter                             ");
            System.out.println("==============================================================");
            System.out.println();
            System.out.println("Input XML: " + xmlFile);
            System.out.println();
            
            // Transform to HTML visualization
            System.out.println("Generating HTML visualization...");
            String htmlFile = "ast-visualization.html";
            
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            
            // Load XSLT from resources
            InputStream xsltStream = AstXmlToHtmlConverter.class
                .getResourceAsStream("/xslt/ast-to-html.xsl");
            
            if (xsltStream == null) {
                System.err.println("ERROR: Could not find ast-to-html.xsl in resources");
                System.err.println("Make sure to run: mvn compile");
                System.exit(1);
            }
            
            Transformer htmlTransformer = transformerFactory
                .newTransformer(new StreamSource(xsltStream));
            
            htmlTransformer.transform(
                new StreamSource(new File(xmlFile)),
                new StreamResult(new File(htmlFile))
            );
            
            System.out.println("  [OK] HTML visualization saved to: " + htmlFile);
            System.out.println();
            
            // Print summary
            System.out.println("==============================================================");
            System.out.println("                    SUCCESS                                   ");
            System.out.println("==============================================================");
            System.out.println("Generated: " + htmlFile);
            System.out.println();
            System.out.println("Open in browser to view the AST visualization.");
            
        } catch (TransformerException e) {
            System.err.println();
            System.err.println("==============================================================");
            System.err.println("                     ERROR                                    ");
            System.err.println("==============================================================");
            System.err.println();
            System.err.println("Error type: " + e.getClass().getSimpleName());
            System.err.println("Message: " + e.getMessage());
            System.err.println();
            if (e.getCause() != null) {
                System.err.println("Caused by: " + e.getCause().getMessage());
            }
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            System.err.println();
            System.err.println("==============================================================");
            System.err.println("                     ERROR                                    ");
            System.err.println("==============================================================");
            System.err.println();
            System.err.println("Error type: " + e.getClass().getSimpleName());
            System.err.println("Message: " + e.getMessage());
            System.err.println();
            e.printStackTrace();
            System.exit(1);
        }
    }
}
